# Generated by Django 6.0.3 on 2026-03-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
